"""empty message

Revision ID: cb0b41df66ce
Revises: 8e3c20e94142
Create Date: 2023-05-22 08:57:56.356738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb0b41df66ce'
down_revision = '8e3c20e94142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subcategory', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('storefront_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['storefront_id'], ['storefronts.id'], name=op.f('fk_products_storefront_id_storefronts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('name', name=op.f('uq_products_name'))
    )
    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image1', sa.String(length=500), nullable=True),
    sa.Column('image2', sa.String(length=500), nullable=True),
    sa.Column('image3', sa.String(length=500), nullable=True),
    sa.Column('image4', sa.String(length=500), nullable=True),
    sa.Column('image5', sa.String(length=500), nullable=True),
    sa.Column('image6', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_images_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_images')),
    sa.UniqueConstraint('product_id', name=op.f('uq_product_images_product_id'))
    )
    with op.batch_alter_table('storefronts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=40), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storefronts', schema=None) as batch_op:
        batch_op.drop_column('name')

    op.drop_table('product_images')
    op.drop_table('products')
    # ### end Alembic commands ###
