"""empty message

Revision ID: f132d95e400e
Revises: 74a392933347
Create Date: 2023-05-19 17:12:50.461576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f132d95e400e'
down_revision = '74a392933347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.String(length=255), nullable=False))
        batch_op.drop_constraint('uq_product_images_product_name', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_product_images_product_id'), ['product_id'])
        batch_op.drop_constraint('fk_product_images_product_name_products', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_product_images_product_id_products'), 'products', ['product_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('product_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_product_images_product_id_products'), type_='foreignkey')
        batch_op.create_foreign_key('fk_product_images_product_name_products', 'products', ['product_name'], ['name'], ondelete='CASCADE')
        batch_op.drop_constraint(batch_op.f('uq_product_images_product_id'), type_='unique')
        batch_op.create_unique_constraint('uq_product_images_product_name', ['product_name'])
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###
