"""empty message

Revision ID: a0c55563c386
Revises: 81e81bf3a3ea
Create Date: 2023-05-29 17:27:26.923055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0c55563c386'
down_revision = '81e81bf3a3ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('uq_reviews_user_id', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_reviews_user_id', ['user_id', 'product_id'])

    # ### end Alembic commands ###
