"""empty message

Revision ID: 30a890dbe559
Revises: fd7511d2567b
Create Date: 2023-05-24 18:12:20.174594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30a890dbe559'
down_revision = 'fd7511d2567b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('uq_reviews_user_id', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_reviews_product_id'), ['product_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_reviews_product_id'), type_='unique')
        batch_op.create_unique_constraint('uq_reviews_user_id', ['user_id'])

    # ### end Alembic commands ###
