"""empty message

Revision ID: fd7511d2567b
Revises: 09dcd592ff62
Create Date: 2023-05-24 18:07:50.152992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd7511d2567b'
down_revision = '09dcd592ff62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_reviews_user_id'), ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_reviews_user_id'), type_='unique')

    # ### end Alembic commands ###
