"""empty message

Revision ID: 528a6ec50546
Revises: 30a890dbe559
Create Date: 2023-05-26 10:33:56.878248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '528a6ec50546'
down_revision = '30a890dbe559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('uq_reviews_product_id', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_reviews_user_id'), ['user_id', 'product_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_reviews_user_id'), type_='unique')
        batch_op.create_unique_constraint('uq_reviews_product_id', ['product_id'])

    # ### end Alembic commands ###
