"""empty message

Revision ID: 1583afb1ea56
Revises: 8adf851491be
Create Date: 2023-05-19 10:38:52.160219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1583afb1ea56'
down_revision = '8adf851491be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_product_images_product_id'), ['product_id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_products_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_products_name'), type_='unique')

    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_product_images_product_id'), type_='unique')

    # ### end Alembic commands ###
