"""empty message

Revision ID: 309106d4d2f0
Revises: b4ad25985752
Create Date: 2023-05-18 12:06:51.534774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '309106d4d2f0'
down_revision = 'b4ad25985752'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('uq_products_storefront_id', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_products_storefront_id', ['storefront_id'])

    # ### end Alembic commands ###
