"""empty message

Revision ID: 27ee6dc09a39
Revises: a0c55563c386
Create Date: 2023-05-30 01:53:45.808400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27ee6dc09a39'
down_revision = 'a0c55563c386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_reviews_user_id'), ['user_id', 'product_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_reviews_user_id'), type_='unique')

    # ### end Alembic commands ###
