"""empty message

Revision ID: 8adf851491be
Revises: 309106d4d2f0
Create Date: 2023-05-18 15:18:10.624040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8adf851491be'
down_revision = '309106d4d2f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image1', sa.String(length=500), nullable=True),
    sa.Column('image2', sa.String(length=500), nullable=True),
    sa.Column('image3', sa.String(length=500), nullable=True),
    sa.Column('image4', sa.String(length=500), nullable=True),
    sa.Column('image5', sa.String(length=500), nullable=True),
    sa.Column('image6', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_images_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_images'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_images')
    # ### end Alembic commands ###
